src/app/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from app.views import IndexBasedView, searchbar, Login, Logout, Registration, \
    ResetPasswordView, ActivateUser, ProfileView

app_name = "app"

urlpatterns = [
    path('', IndexBasedView.as_view(), name='index'),
    path("search/", searchbar, name="searchbar"),
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
    path("signup/", Registration.as_view(), name="registration"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUser.as_view(), name="activate_user"),
    path(
        "password-reset/",
        ResetPasswordView.as_view(),
        name="password_reset"
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path('profile/', ProfileView.as_view(), name="profile"),

]

src/config/urls.py
from django.conf.urls.static import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('oauth/', include('social_django.urls', namespace="social")),
    path('accounts/', include('phone_auth.urls', namespace="phone_auth")),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = "app.views.handle404"
handler403 = 'app.views.custom_permission_denied_view'

src/groups/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf.urls.static import settings
from .views import ListOfGroupView, CreateGroupView, UpdateGroupView, DeleteGroupView

app_name = "groups"

urlpatterns = [
    path('', ListOfGroupView.as_view(), name='get_all_groups'),
    path('create/', CreateGroupView.as_view(), name='create_group'),
    path("update/<int:pk>/", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<int:pk>/", DeleteGroupView.as_view(), name="delete_group"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/students/urls.py
from django.urls import path
from .views import StudentListView, CreateStudentView, UpdateStudentView, DeleteStudentView

app_name = "students"

urlpatterns = [
    path('', StudentListView.as_view(), name='all_students'),
    path('create/', CreateStudentView.as_view(), name='create_student'),
    path("update/<uuid:pk>/", UpdateStudentView.as_view(), name="update_student"),
    path("delete/<uuid:pk>/", DeleteStudentView.as_view(), name="delete_student"),
]

src/teachers/urls.py
from django.urls import path
from .views import TeacherListView, CreateTeacherView, UpdateTeacherView, DeleteTeacherView


app_name = "teachers"

urlpatterns = [
    path('', TeacherListView.as_view(), name='get_all_teachers'),
    path('create/', CreateTeacherView.as_view(), name='create_teacher'),
    path("update/<int:pk>/", UpdateTeacherView.as_view(), name="update_teacher"),
    path("delete/<int:pk>/", DeleteTeacherView.as_view(), name="delete_teacher"),
]

src/templates/basic/index.html
{% load static %}
<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.101.0">
    {% block title %}
        <title>LMS</title>
    {% endblock %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/cover/">
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
        a {
            text-decoration: none;
            margin-left: 10px;
        }

        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }

    </style>
    <link href="cover.css" rel="stylesheet">
</head>
<body class="d-flex h-100 text-center text-bg-dark">

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">

    <header class="p-3 mb-3 border-bottom">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
                    <h3 class="float-md-start mb-0"><a href="{% url 'app:index' %}">LMS</a></h3>
                </a>
                {% if user.is_authenticated %}
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="{% url 'students:all_students' %}" class="nav-link px-2">Students</a></li>
                    <li><a href="{% url 'teachers:get_all_teachers' %}" class="nav-link px-2 ">Teachers</a></li>
                    <li><a href="{% url 'groups:get_all_groups' %}" class="nav-link px-2">Groups</a></li>
                </ul>

                <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" action="{% url 'app:searchbar' %}"
                      method="get">
                    <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
                </form>

                    <div class="dropdown text-end">
                        <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            {% if user.avatar %}
                                <img src="{{ user.avatar }}" alt="mdo"
                                 class="rounded-circle" width="32" height="32">
                            {% else %}
                                <img src="https://github.com/mdo.png" alt="mdo"
                                 class="rounded-circle" width="32" height="32">
                            {% endif %}
                        </a>
                        <ul class="dropdown-menu text-small">
                            <li><a class="dropdown-item" href="#">{{ user.email }}</a></li>
                            <li><a class="dropdown-item" href="{% url 'app:profile' %}">Profile</a></li>
                            {% if user.is_staff %}
                                <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin page</a></li>
                            {% endif %}
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'app:password_reset' %}">Change password</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url "app:logout" %}">Logout</a></li>
                        </ul>
                    </div>
                {% else %}
                    <div class="dropdown text-end">
                        <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
                        </a>
                        <ul class="dropdown-menu text-small">
                            <li><a class="dropdown-item" href="{% url "app:login" %}">Login</a></li>
                            <li><a class="dropdown-item" href="{% url "app:registration" %}">Sign up</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Reset password</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'social:begin' backend='github' %}">GitHub</a></li>
                            <li><a class="dropdown-item" href="{% url 'social:begin' backend='linkedin-oauth2' %}">LinkedIn</a></li>
                        </ul>
                    </div>
                {% endif %}
            </div>
        </div>
    </header>
    {{ message }}
    {% block content %}
    {% endblock %}

    <footer class="mt-auto text-white-50">
    </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

src/templates/basic/searchbar.html
{% extends "basic/index.html" %}

{% block content %}
{% if post %}
    <table class="table table-dark table-striped">
      <thead>
        <tr>
          <th scope="col">id</th>
          <th scope="col">First name</th>
          <th scope="col">Last name</th>
          <th scope="col">Email</th>
          <th scope="col">Grade</th>
          <th scope="col">Age</th>
          <th scope="col">Birthday</th>
          <th scope="col">Group</th>
        </tr>
      </thead>
      <tbody>
      {% for student in post %}
        <tr>
          <th scope="row"><img height="50" width="50" src="{{ student.avatar.url }}" alt="avatar"></th>
          <td>{{ student.first_name }}</td>
          <td>{{ student.last_name }}</td>
          <td>{{ student.email }}</td>
          <td>{{ student.grade }}</td>
            {% if student.birthday %}
                <td>{{ student.age }}</td>
                <td>{{ student.birthday }}</td>
            {% else %}
                <td>Undefined</td>
                <td>Undefined</td>
            {% endif %}
          <td>{{ student.group }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
{% else %}
    <h1>Nothing find</h1>
{% endif %}

{% endblock %}