src/app/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from app.views import IndexBasedView, searchbar, Login, Logout, Registration, \
    ResetPasswordView, ActivateUser, ProfileView

app_name = "app"

urlpatterns = [
    path('', IndexBasedView.as_view(), name='index'),
    path("search/", searchbar, name="searchbar"),
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
    path("signup/", Registration.as_view(), name="registration"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUser.as_view(), name="activate_user"),
    path(
        "password-reset/",
        ResetPasswordView.as_view(),
        name="password_reset"
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path('profile/', ProfileView.as_view(), name="profile"),

]

src/config/urls.py
from django.conf.urls.static import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('oauth/', include('social_django.urls', namespace="social")),
    path('accounts/', include('phone_auth.urls', namespace="phone_auth")),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = "app.views.handle404"
handler403 = 'app.views.custom_permission_denied_view'

src/students/urls.py
from django.urls import path
from .views import StudentListView, CreateStudentView, UpdateStudentView, DeleteStudentView

app_name = "students"

urlpatterns = [
    path('', StudentListView.as_view(), name='all_students'),
    path('create/', CreateStudentView.as_view(), name='create_student'),
    path("update/<uuid:pk>/", UpdateStudentView.as_view(), name="update_student"),
    path("delete/<uuid:pk>/", DeleteStudentView.as_view(), name="delete_student"),
]

src/students/models.py
from uuid import uuid4

from django.db import models

from app.models import Person
from groups.models import Group
from .validators import file_size, file_extension


class Student(Person):
    uuid = models.UUIDField(
        primary_key=True,
        editable=False,
        default=uuid4,
        unique=True,
        db_index=True
    )
    avatar = models.ImageField(upload_to="media/students/avatar", null=True)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name="students")
    grade = models.PositiveSmallIntegerField(default=0, null=True)
    resume = models.FileField(upload_to='media/docs',
                              null=True,
                              validators=[file_size, file_extension])

    def __str__(self):
        return f'{self.first_name} {self.last_name} {self.email}'

src/students/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django import forms

from .models import Student


class StudentForm(ModelForm):
    class Meta:
        model = Student
        birthday = forms.DateField()
        fields = "__all__"

    @staticmethod
    def normalize_text(text: str) -> str:
        return text.strip().capitalize()

    def clean_email(self):
        email = self.cleaned_data["email"]

        if "@yandex" in email.lower():
            raise ValidationError("Yandex domain is forbidden in our country")

        return email

    def clean_first_name(self):
        return self.normalize_text(self.cleaned_data["first_name"])

    def clean_last_name(self):
        return self.normalize_text(self.cleaned_data["last_name"])

    def clean(self):
        cleaned_data = super().clean()

        first_name = cleaned_data["first_name"]
        last_name = cleaned_data["last_name"]

        if first_name == last_name:
            raise ValidationError("First name and last name can`t be equal")

        return cleaned_data

src/students/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from .forms import StudentForm
from .models import Student


class StudentListView(ListView):
    model = Student
    template_name = "students/students_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        students = Student.objects.all()
        context["students"] = students
        return context


class CreateStudentView(CreateView):
    model = Student
    template_name = "students/students_create.html"
    form_class = StudentForm
    success_url = reverse_lazy("students:all_students")


class UpdateStudentView(UpdateView):
    model = Student
    form_class = StudentForm
    template_name = "students/update_students.html"
    success_url = reverse_lazy("students:all_students")


class DeleteStudentView(DeleteView):
    model = Student
    success_url = reverse_lazy("students:all_students")

src/templates/students/students_create.html
{% extends "basic/../basic/index.html" %}
{% load crispy_forms_tags %}

{% block content %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary" value="Create" >Create</button>
</form>

{% endblock content %}

src/templates/students/students_list.html
{% extends "basic/../basic/index.html" %}

{% block content %}
<p><a class="btn btn-primary float-xl-start" href="{% url 'students:create_student' %}">Create</a></p>

<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">Avatar</th>
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col">Email</th>
      <th scope="col">Grade</th>
      <th scope="col">Age</th>
      <th scope="col">Birthday</th>
      <th scope="col">Group</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
  {% for student in students %}
    <tr>
      <th scope="row"><img height="50" width="50" src="{{ student.avatar.url }}" alt="No avatar"></th>
      <td>{{ student.first_name }}</td>
      <td>{{ student.last_name }}</td>
      <td>{{ student.email }}</td>
      <td>{{ student.grade }}</td>
        {% if student.birthday %}
            <td>{{ student.age }}</td>
            <td>{{ student.birthday }}</td>
        {% else %}
            <td>Undefined</td>
            <td>Undefined</td>
        {% endif %}
        <td>{{ student.group }}</td>
        <td><a type="button" class="btn btn-warning" href="{% url 'students:update_student' student.pk %}">Edit</a></td>
        <td><a type="button" class="btn btn-danger" href="{% url 'students:delete_student' student.pk %}">Delete</a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

src/templates/students/update_students.html
{% extends "basic/../basic/index.html" %}
{% load crispy_forms_tags %}

{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary" value="Update" >Update</button>
</form>

{% endblock content %}