src/app/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from app.views import IndexBasedView, searchbar, Login, Logout, Registration, \
    ResetPasswordView, ActivateUser, ProfileView

app_name = "app"

urlpatterns = [
    path('', IndexBasedView.as_view(), name='index'),
    path("search/", searchbar, name="searchbar"),
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
    path("signup/", Registration.as_view(), name="registration"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUser.as_view(), name="activate_user"),
    path(
        "password-reset/",
        ResetPasswordView.as_view(),
        name="password_reset"
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path('profile/', ProfileView.as_view(), name="profile"),

]

src/config/urls.py
from django.conf.urls.static import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('oauth/', include('social_django.urls', namespace="social")),
    path('accounts/', include('phone_auth.urls', namespace="phone_auth")),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = "app.views.handle404"
handler403 = 'app.views.custom_permission_denied_view'

src/groups/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf.urls.static import settings
from .views import ListOfGroupView, CreateGroupView, UpdateGroupView, DeleteGroupView

app_name = "groups"

urlpatterns = [
    path('', ListOfGroupView.as_view(), name='get_all_groups'),
    path('create/', CreateGroupView.as_view(), name='create_group'),
    path("update/<int:pk>/", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<int:pk>/", DeleteGroupView.as_view(), name="delete_group"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/teachers/urls.py
from django.urls import path
from .views import TeacherListView, CreateTeacherView, UpdateTeacherView, DeleteTeacherView


app_name = "teachers"

urlpatterns = [
    path('', TeacherListView.as_view(), name='get_all_teachers'),
    path('create/', CreateTeacherView.as_view(), name='create_teacher'),
    path("update/<int:pk>/", UpdateTeacherView.as_view(), name="update_teacher"),
    path("delete/<int:pk>/", DeleteTeacherView.as_view(), name="delete_teacher"),
]

src/teachers/models.py
from datetime import datetime

from django.db import models

from groups.models import Group


class Teacher(models.Model):
    avatar = models.ImageField(upload_to="static/img", null=True)
    full_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    created_at = models.DateTimeField(default=datetime.now)
    updated_at = models.DateTimeField(default=datetime.now, null=True)
    group = models.ManyToManyField(Group, related_name="teachers")

    def __str__(self):
        return self.full_name

src/teachers/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from .models import Teacher


class TeacherForm(ModelForm):
    class Meta:
        model = Teacher
        fields = ["avatar", "full_name", "email", "phone", "address", "group"]

    @staticmethod
    def normalize_text(text: str) -> str:
        return text.strip().capitalize()

    def clean_email(self):
        email = self.cleaned_data["email"]

        if "@yandex" in email.lower():
            raise ValidationError("Yandex domain is forbidden in our country")

        return email

    def clean_full_name(self):
        return self.normalize_text(self.cleaned_data["full_name"])

    def clean_address(self):
        return self.normalize_text(self.cleaned_data["address"])

src/teachers/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from .forms import TeacherForm
from .models import Teacher


class TeacherListView(ListView):
    model = Teacher
    template_name = "teachers/teachers_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        teachers = Teacher.objects.all()
        context["teachers"] = teachers
        return context


class CreateTeacherView(CreateView):
    model = Teacher
    template_name = "teachers/create_teachers.html"
    form_class = TeacherForm
    success_url = reverse_lazy('teachers:get_all_teachers')


class UpdateTeacherView(UpdateView):
    model = Teacher
    template_name = "teachers/update_teacher.html"
    form_class = TeacherForm
    success_url = reverse_lazy('teachers:get_all_teachers')


class DeleteTeacherView(DeleteView):
    model = Teacher
    success_url = reverse_lazy('teachers:get_all_teachers')

src/templates/teachers/create_teachers.html
{% extends "basic/../basic/index.html" %}
{% load crispy_forms_tags %}

{% block content %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary" value="Create" >Create</button>
</form>

{% endblock content %}

src/templates/teachers/teachers_list.html
{% extends "basic/../basic/index.html" %}

{% block content %}
<p><a class="btn btn-primary float-xl-start" href="{% url 'teachers:create_teacher' %}">Create</a></p>

<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">Avatar</th>
      <th scope="col">Full name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Address</th>
      <th scope="col">Groups</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
{% for g in teacher.group.all %}
            <td>{{ g }}</td>
        {% endfor %}
  <tbody>
  {% for teacher in teachers %}
    <tr>
      <th scope="row"><img height="50" width="50" src="{{ teacher.avatar.url }}" alt="No image"></th>
      <td>{{ teacher.full_name }}</td>
      <td>{{ teacher.email }}</td>
      <td>{{ teacher.phone }}</td>
      <td>{{ teacher.address }}</td>
      <td>
          {% for g in teacher.group.all %}
              <a href="{% url 'groups:get_all_groups' %}">{{ g }}</a><br>
          {% endfor %}
      </td>
      <td><a type="button" class="btn btn-warning" href="{% url 'teachers:update_teacher' teacher.pk %}">Edit</a></td>
      <td>
          <form method="POST" action="{% url "teachers:delete_teacher" teacher.pk %}">
            {% csrf_token %}<input class="btn btn-danger" type="submit" value="Delete">
          </form>
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

src/templates/teachers/update_teacher.html
{% extends "basic/../basic/index.html" %}
{% load crispy_forms_tags %}

{% block content %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary" value="Update" >Update</button>
</form>

{% endblock content %}