src/app/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from app.views import IndexBasedView, searchbar, Login, Logout, Registration, \
    ResetPasswordView, ActivateUser, ProfileView

app_name = "app"

urlpatterns = [
    path('', IndexBasedView.as_view(), name='index'),
    path("search/", searchbar, name="searchbar"),
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
    path("signup/", Registration.as_view(), name="registration"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUser.as_view(), name="activate_user"),
    path(
        "password-reset/",
        ResetPasswordView.as_view(),
        name="password_reset"
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path('profile/', ProfileView.as_view(), name="profile"),

]

src/config/urls.py
from django.conf.urls.static import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('oauth/', include('social_django.urls', namespace="social")),
    path('accounts/', include('phone_auth.urls', namespace="phone_auth")),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = "app.views.handle404"
handler403 = 'app.views.custom_permission_denied_view'

src/groups/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf.urls.static import settings
from .views import ListOfGroupView, CreateGroupView, UpdateGroupView, DeleteGroupView

app_name = "groups"

urlpatterns = [
    path('', ListOfGroupView.as_view(), name='get_all_groups'),
    path('create/', CreateGroupView.as_view(), name='create_group'),
    path("update/<int:pk>/", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<int:pk>/", DeleteGroupView.as_view(), name="delete_group"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/groups/models.py
from datetime import datetime

from django.db import models


class Group(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    about = models.TextField(blank=True)
    logo = models.ImageField(upload_to='static/img', blank=True, null=True)
    created_at = models.DateTimeField(default=datetime.now, blank=True)
    updated_at = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.name

src/groups/forms.py
from django.forms import ModelForm

from .models import Group


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = ("name", "description", "about", "logo")

src/groups/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from .forms import GroupForm
from .models import Group


class ListOfGroupView(ListView):
    model = Group
    template_name = "groups/get_all_groups.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        groups = Group.objects.all()
        context["groups"] = groups
        return context


class CreateGroupView(CreateView):
    model = Group
    template_name = "groups/create_group.html"
    form_class = GroupForm
    success_url = reverse_lazy("groups:get_all_groups")


class UpdateGroupView(UpdateView):
    model = Group
    template_name = "groups/update_group.html"
    form_class = GroupForm
    success_url = reverse_lazy("groups:get_all_groups")


class DeleteGroupView(DeleteView):
    model = Group
    success_url = reverse_lazy("groups:get_all_groups")

src/templates/groups/create_group.html
{% extends "basic/../basic/index.html" %}
{% load crispy_forms_tags %}

{% block content %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary" value="Create" >Create</button>
</form>

{% endblock content %}

src/templates/groups/get_all_groups.html
{% extends "basic/../basic/index.html" %}

{% block content %}
<p><a class="btn btn-primary float-xl-start" href="{% url 'groups:create_group' %}">Create</a></p>

<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">About</th>
      <th scope="col">Logo</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
  {% for group in groups %}
    <tr>
      <th scope="row">{{ group.pk }}</th>
      <td>{{ group.name }}</td>
      <td>{{ group.description }}</td>
      <td>{{ group.about }}</td>
      {% if group.logo %}
        <td><img height="50" width="50" src="{{group.logo.url}}" alt="logo_group"></td>
      {% else %}
        <td>-</td>
      {% endif %}
      <td><a type="button" class="btn btn-warning" href="{% url 'groups:update_group' group.pk %}">Edit</a></td>
      <td>
          <form method="POST" action="{% url "groups:delete_group" group.pk %}">
            {% csrf_token %}<input class="btn btn-danger" type="submit" value="Delete">
          </form>
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

src/templates/groups/update_group.html
{% extends "basic/../basic/index.html" %}
{% load crispy_forms_tags %}

{% block content %}

<form method="POST" enctype="multipart/form-data" >
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary" value="Update" >Update</button>
</form>

{% endblock content %}